s/redis/valkey/ single commit with fixes
aiven-sal/valkey-py pull request #2
Opened 2024-05-23 13:19 UTC by aiven-sal

I pretty sure I overlooked something.
But all tests pass locally.
I don't expect the CI to work 100% yet, but we should fix it before we merge.

2024-05-23 14:45 UTC, jfg956 commented on README.md
> +The following is a basic example of a [Redis pipeline](https://valkey.io/docs/manual/pipelining/), a method to optimize round-trip calls, by batching Redis commands, and receiving their results as a
Maybe s/Redis pipeline/Valkey pipeline/.

Also, below is a broken link.
- https://valkey.io/docs/manual/pipelining/

2024-05-23 18:47 UTC, mkmkme requested changes
Thanks a lot for the pull request, Salvatore! Great job!

I've left some of the nitpicks I managed to get during the review. I believe, though, that the only types that actually **have to** be changed before merge are:
1. Automatic changes in words "sto**redis**t" and "**redis**tribution"
2. Links to the old issues
3. An unchanged link to redis.io

Everything else (including multiple references to the "old valkey version" and "old valkey-py version") can be addressed later.

2024-05-23 18:47 UTC, mkmkme commented on valkey/client.py
> +        of valkey-py 3.0, the only lock class we implement is ``Lock`` (which is
Mentioning of valkey-py 3.0

2024-05-23 18:47 UTC, mkmkme commented on valkey/cluster.py
> +        of valkey-py 3.0, the only lock class we implement is ``Lock`` (which is
>valkey-py 3.0

2024-05-23 18:47 UTC, mkmkme commented on valkey/cluster.py
> +        NOTE: Due to a bug in valkey<7.0, this function does not work properly
>valkey<7.0

2024-05-23 18:47 UTC, mkmkme commented on valkey/cluster.py
> +        Taken code from valkey-py and tweak to make it work within a cluster.
Should the origin of the code be changed? :)

2024-05-23 18:47 UTC, mkmkme commented on valkey/commands/core.py
> +        timestamp in milliseconds in which the key will expire. (Valkey 5.0 or
>Valkey 5.0

2024-05-23 18:47 UTC, mkmkme commented on valkey/commands/core.py
> +            (Available since Valkey 6.0)
>Valkey 6.0

>Valkey 6.2

2024-05-23 18:47 UTC, mkmkme commented on valkey/commands/core.py
> +        Valkey 2.6+.
The note about version is not needed here

2024-05-23 18:47 UTC, mkmkme commented on valkey/commands/core.py
> +        # because it was supported in 3.5.3 (of valkey-py)
Mentionings of valkey-py 3.5.3 and "old valkey version"

2024-05-23 18:47 UTC, mkmkme commented on valkey/commands/core.py
> +    https://valkey.com/ebook/part-3-next-steps/chapter-11-scripting-valkey-with-lua/
I think this should be replaced with some documentation page later

2024-05-23 18:47 UTC, mkmkme commented on valkey/commands/core.py
> +        # Valkey pre 6 had no sync_type.
Not needed.

2024-05-23 18:47 UTC, mkmkme commented on valkey/commands/core.py
> +        stovalkeyt: bool = False,
This shouldn't be changed

2024-05-23 18:47 UTC, mkmkme commented on valkey/commands/graph/__init__.py
> +                "RedisGraph support is deprecated as of Valkey Stack 7.2 \
Need to create a ticket for the future to address this

2024-05-23 18:47 UTC, mkmkme commented on valkey/commands/search/commands.py
> +        version="2.0.0", reason="deprecated since valkeyearch 2.0, call hset instead"
RediSearch got automatically replaced. Probably also need to create a ticket for the future

2024-05-23 18:47 UTC, mkmkme commented on valkey/exceptions.py
> +    For more information see `Memory optimization in Valkey <https://redis.io/docs/management/optimization/memory-optimization/#memory-allocation>`_. # noqa
Links to redis.io

2024-05-23 18:47 UTC, mkmkme commented on whitelist.py
Some of your changes change also the formatting, which means some of these lines might be off. Did you check them?

2024-05-23 18:48 UTC, mkmkme commented on .github/wordlist.txt
> +sexualized
:eyes:

2024-05-23 18:50 UTC, mkmkme commented on README.md
> +The following is a basic example of a [Redis pipeline](https://valkey.io/docs/manual/pipelining/), a method to optimize round-trip calls, by batching Redis commands, and receiving their results as a
Quite a lot of links are currently broken. I think we can address them later, because:
1. If we wait for them to appear, this PR will not be merged for a very long time
2. If we remove the broken links right now, we might forget to add them later

2024-05-23 19:43 UTC, ahmedsobeh commented on docs/advanced_features.rst
> +`Sharded pubsub <https://valkey.io/docs/interact/pubsub/#:~:text=Sharded%20Pub%2FSub%20helps%20to,the%20shard%20of%20a%20cluster.>`_ is a feature introduced with Valkey 7.0, and fully supported by va
should be deleted?

2024-05-23 19:43 UTC, ahmedsobeh commented on docs/advanced_features.rst
> +Older versions of valkey-py only read messages with pubsub.listen().
+1, should we delete this line?

2024-05-24 08:37 UTC, aiven-sal commented on .github/wordlist.txt
> +sexualized
It's a word used in Valkey's CoC. GitHub's spellchecker thinks it's made-up.

2024-05-24 08:41 UTC, aiven-sal commented on README.md
> +The following is a basic example of a [Redis pipeline](https://valkey.io/docs/manual/pipelining/), a method to optimize round-trip calls, by batching Redis commands, and receiving their results as a
I could just make them point to the old Redis documentation, until we have something specific to Valkey to point to.

2024-05-24 08:55 UTC, aiven-sal commented on docs/conf.py
> +copyright = f"{current_year}, Valkey Inc"
We certainly to the non-existent Valkey Inc. But LF does not own any copyright here either. That said I don't think the Redis Inc actually owns the copyright on everything (AFAIK there is no CLA with redis-py). Maybe this should simply be "valkey-py contributors" ?

2024-05-24 09:01 UTC, aiven-sal commented on docs/examples/search_vector_similarity_examples.ipynb
> +    "Find more example apps, tutorials, and projects using Valkey Vector Similarity Search [in this GitHub organization](https://github.com/ValkeyVentures)."
Who knows? I'll revert the change for now. The whole example doesn't actually work with Valkey, but I'd rather keep it for the moment, maybe it will work soon.

2024-05-24 09:08 UTC, aiven-sal commented on docs/redismodules.rst
> +Accessing valkey module commands requires the installation of the supported `Valkey module <https://docs.valkey.com/latest/modules/>`_. For a quick start with valkey modules, try the `Valkeymod docke
Maybe I should completely remove this file, none of the things documented here can work with Valkey. I'm not too keen on removing the code that might be useful in the future, but the doc probably shouldn't contain this stuff.

2024-05-24 09:09 UTC, mkmkme commented on docs/redismodules.rst
> +Accessing valkey module commands requires the installation of the supported `Valkey module <https://docs.valkey.com/latest/modules/>`_. For a quick start with valkey modules, try the `Valkeymod docke
It's also called **redis**modules.rst :)

2024-05-24 09:18 UTC, aiven-sal commented on tests/conftest.py
> +def skip_if_valkey_enterprise() -> _TestDecorator:
It isn't!

2024-05-24 09:53 UTC, aiven-sal commented on tests/test_asyncio/test_cluster.py
> +        rc = ValkeyCluster.from_url(url)
I think we might rename those variables, also to avoid using single-letter variables, but maybe we can do this in a future cleanup?

2024-05-24 09:54 UTC, mkmkme commented on tests/test_asyncio/test_cluster.py
> +        rc = ValkeyCluster.from_url(url)
Sure, let's leave them for now

2024-05-24 12:10 UTC, aiven-sal commented on valkey/asyncio/cluster.py
> +        # valkey server to parse the keys. Besides, there is a bug in valkey<7.0
This comment is about a workaround for a bug I'm not familiar with. Maybe it's better to remove the comment and the workaround in a separate PR.

2024-05-24 12:14 UTC, aiven-sal commented on valkey/cluster.py
> +        NOTE: Due to a bug in valkey<7.0, this function does not work properly
As above, I'd keep this comment until we also get around to change the code appropriately.

2024-05-24 12:16 UTC, aiven-sal commented on valkey/cluster.py
> +        Taken code from valkey-py and tweak to make it work within a cluster.
I wonder what this comment meant in the first place, but I'll revert the change.

2024-05-24 12:17 UTC, mkmkme commented on valkey/cluster.py
> +        Taken code from valkey-py and tweak to make it work within a cluster.
My guess is that initially it was copy-pasted from redis-py to some other project that would support redis-cluster and then copy-pasted to redis-py as is.

2024-05-24 12:29 UTC, aiven-sal commented on valkey/exceptions.py
> +    For more information see `Memory optimization in Valkey <https://redis.io/docs/management/optimization/memory-optimization/#memory-allocation>`_. # noqa
Yep, this is intended, there is no such page in Valkey's doc AFAIK.

2024-05-24 12:30 UTC, mkmkme commented on valkey/exceptions.py
> +    For more information see `Memory optimization in Valkey <https://redis.io/docs/management/optimization/memory-optimization/#memory-allocation>`_. # noqa
Oh I see!

2024-05-24 13:04 UTC, aiven-sal commented on whitelist.py
They were already wrong as far as I can tell.

2024-05-24 13:18 UTC, aiven-sal commented on README.md
> +The [official Redis command documentation](https://valkey.io/commands)
It should be fixed
https://github.com/aiven-sal/valkey-py/pull/2/commits/d3917cb5974005463384869ca0cd17d682cc57a8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L80
but GH shows the old code anyway.

2024-05-24 13:56 UTC, mkmkme requested changes
Most of the comments have been fixed, but I still found a couple of places that should be changed before we merge this one

2024-05-24 13:56 UTC, mkmkme commented on docs/examples/opentelemetry/requirements.txt
> +valkey
Since the version was explicitly pinned to 4.3.4, there's a chance this example will not work.

But I guess we can fix it later.

2024-05-24 13:56 UTC, mkmkme commented on docs/opentelemetry.rst
> +You can use Uptrace to monitor valkey-py using this `GitHub example <https://github.com/valkey/valkey-py/tree/master/docs/examples/opentelemetry>`_ as a starting point.
Should be `valkey-io/valkey-py` here

2024-05-24 13:56 UTC, mkmkme commented on docs/resp3_features.rst
> +valkey-py supports the `RESP 3 standard <https://github.com/valkey/valkey-specifications/blob/master/protocol/RESP3.md>`_. Practically, this means that client using RESP 3 will be faster and more per
Should be `valkey-io/valkey-specifications` likely

2024-05-24 13:56 UTC, mkmkme commented on docs/resp3_features.rst
> +Push notifications are a way that valkey sends out of band data. The RESP 3 protocol includes a `push type <https://github.com/valkey/valkey-specifications/blob/master/protocol/RESP3.md#push-type>`_
ditto

2024-05-24 13:56 UTC, mkmkme commented on tests/conftest.py
>              id_str = str(client.client_id())
Probably makes sense to leave only the part under `if` as situation otherwise is unlikely

2024-05-24 13:56 UTC, mkmkme commented on tests/test_asyncio/conftest.py
> +        id_str = f"{random.randrange(2 ** 32):08x}"
Here you left the part under `else`, which is the part that should work with `redis<5.0`. I think you should've left the other one, with `await client.client_id()`

2024-05-24 13:56 UTC, mkmkme commented on tests/test_connection_pool.py
> +        # Redis < 6
I wonder if this part should be dropped completely and the second one should lose the comment. 

I don't think we're going to run `valkey-py` with Redis, especially the older one.

2024-05-24 13:56 UTC, mkmkme commented on valkey/_parsers/base.py
> +    # Redis < 6.0
Here also, the first part should lose the comment, the second part should be dropped

2024-05-24 13:56 UTC, mkmkme commented on tests/test_asyncio/testdata/titles.csv
> +intramolecular vibrational energy valkeytribution,1
@aiven-sal this is still wrong

2024-05-24 13:56 UTC, mkmkme commented on tests/testdata/titles.csv
> -intramolecular vibrational energy redistribution,1
@aiven-sal this is still wrong

2024-05-24 14:04 UTC, aiven-sal commented on docs/examples/opentelemetry/requirements.txt
> +valkey
I suspect that this wouldn't have worked even if we had the right version. I _think_ that maybe some work on opentelemetry side is also needed.

2024-05-24 14:05 UTC, mkmkme commented on docs/examples/opentelemetry/requirements.txt
> +valkey
Yeah let's leave this one for later

2024-05-24 14:08 UTC, aiven-sal commented on docs/resp3_features.rst
> +valkey-py supports the `RESP 3 standard <https://github.com/valkey/valkey-specifications/blob/master/protocol/RESP3.md>`_. Practically, this means that client using RESP 3 will be faster and more per
Actually I should probably just point to redis doc, because valkey's doesn't exist

2024-05-24 14:10 UTC, aiven-sal commented on tests/test_connection_pool.py
> +        # Redis < 6
I started removing that kind of code and ended up in a deep rabbit hole, I think it's better to leave this cleanups to future PRs. This one is quite big already.

2024-05-24 14:10 UTC, aiven-sal commented on valkey/_parsers/base.py
> +    # Redis < 6.0
as above

2024-05-27 09:12 UTC, mkmkme approved these changes
LGTM.

Thanks again for the great job!

2024-05-27 09:45 UTC, aiven-sal commented on README.md
> +The [official Redis command documentation](https://valkey.io/commands)
can this be marked as resolved?

2024-05-27 10:08 UTC, merged